// <auto-generated />
using System;
using ApiPeliculas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(PeliculaContext))]
    [Migration("20240301162851_MigracionconDatosDefecto")]
    partial class MigracionconDatosDefecto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiPeliculas.Modelos.Butaca", b =>
                {
                    b.Property<int>("ButacaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ButacaID"), 1L, 1);

                    b.Property<int>("SalaID")
                        .HasColumnType("int");

                    b.HasKey("ButacaID");

                    b.HasIndex("SalaID");

                    b.ToTable("Butacas");

                    b.HasData(
                        new
                        {
                            ButacaID = 1,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 2,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 3,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 4,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 5,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 6,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 7,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 8,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 9,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 10,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 11,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 12,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 13,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 14,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 15,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 16,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 17,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 18,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 19,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 20,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 21,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 22,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 23,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 24,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 25,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 26,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 27,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 28,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 29,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 30,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 31,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 32,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 33,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 34,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 35,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 36,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 37,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 38,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 39,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 40,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 41,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 42,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 43,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 44,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 45,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 46,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 47,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 48,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 49,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 50,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 51,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 52,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 53,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 54,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 55,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 56,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 57,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 58,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 59,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 60,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 61,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 62,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 63,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 64,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 65,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 66,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 67,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 68,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 69,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 70,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 71,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 72,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 73,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 74,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 75,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 76,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 77,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 78,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 79,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 80,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 81,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 82,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 83,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 84,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 85,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 86,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 87,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 88,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 89,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 90,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 91,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 92,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 93,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 94,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 95,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 96,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 97,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 98,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 99,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 100,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 101,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 102,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 103,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 104,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 105,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 106,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 107,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 108,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 109,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 110,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 111,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 112,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 113,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 114,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 115,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 116,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 117,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 118,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 119,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 120,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 121,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 122,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 123,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 124,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 125,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 126,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 127,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 128,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 129,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 130,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 131,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 132,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 133,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 134,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 135,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 136,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 137,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 138,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 139,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 140,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 141,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 142,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 143,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 144,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 145,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 146,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 147,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 148,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 149,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 150,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 151,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 152,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 153,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 154,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 155,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 156,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 157,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 158,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 159,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 160,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 161,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 162,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 163,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 164,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 165,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 166,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 167,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 168,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 169,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 170,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 171,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 172,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 173,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 174,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 175,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 176,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 177,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 178,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 179,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 180,
                            SalaID = 3
                        },
                        new
                        {
                            ButacaID = 181,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 182,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 183,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 184,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 185,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 186,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 187,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 188,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 189,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 190,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 191,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 192,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 193,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 194,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 195,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 196,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 197,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 198,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 199,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 200,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 201,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 202,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 203,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 204,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 205,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 206,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 207,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 208,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 209,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 210,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 211,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 212,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 213,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 214,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 215,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 216,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 217,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 218,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 219,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 220,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 221,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 222,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 223,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 224,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 225,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 226,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 227,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 228,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 229,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 230,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 231,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 232,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 233,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 234,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 235,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 236,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 237,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 238,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 239,
                            SalaID = 4
                        },
                        new
                        {
                            ButacaID = 240,
                            SalaID = 4
                        });
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Pelicula", b =>
                {
                    b.Property<int>("PeliculaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeliculaID"), 1L, 1);

                    b.Property<string>("Actores")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PeliculaID");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            PeliculaID = 1,
                            Actores = "Philipe Marcus",
                            Descripcion = "Es una película de acción y ciencia ficción dirigida por Jon Turteltaub y estrenada en 2018. La trama gira en torno a un grupo de científicos que deben detener a un megalodón.",
                            Director = "Jon Turtle",
                            Imagen = "1.jpg",
                            Titulo = "THE MEG 2"
                        },
                        new
                        {
                            PeliculaID = 2,
                            Actores = "Martin Scorsese",
                            Descripcion = "Es una película de ciencia ficción española dirigida por Galder Gaztelu-Urrutia, lanzada en 2019. La película se centra en un centro de reclusión vertical donde los prisioneros están dispuestos en celdas apiladas, y una plataforma de comida desciende a través de los niveles, dejando a los prisioneros de los niveles superiores con menos comida.",
                            Director = "Galder Gaztelu-Urrutia",
                            Imagen = "2.png",
                            Titulo = "EL HOYO"
                        },
                        new
                        {
                            PeliculaID = 3,
                            Actores = "Leonardo DiCaprio",
                            Descripcion = "En el colorido Reino Champiñón, Mario y Luigi disfrutan de una vida tranquila como fontaneros hasta que un día, Bowser, el rey de los Koopas, lanza un malévolo plan para robar todos los champiñones mágicos del reino.",
                            Director = "Martin Scorsese",
                            Imagen = "3.png",
                            Titulo = "SUPER MARIO BROS"
                        },
                        new
                        {
                            PeliculaID = 4,
                            Actores = "Meryl Streep",
                            Descripcion = "Un talentoso piloto de carreras que, después de una serie de eventos inesperados, se encuentra en la oportunidad de su vida: competir en el torneo de carreras 'Gran Turismo'.",
                            Director = "Quentin Tarantino",
                            Imagen = "4.png",
                            Titulo = "GRAN TURISMO"
                        },
                        new
                        {
                            PeliculaID = 5,
                            Actores = "Philipe Marcus",
                            Descripcion = "Es una película de acción y ciencia ficción dirigida por Jon Turteltaub y estrenada en 2018. La trama gira en torno a un grupo de científicos que deben detener a un megalodón.",
                            Director = "Alfred Hitchcock",
                            Imagen = "5.jpg",
                            Titulo = "THE MEG 2"
                        },
                        new
                        {
                            PeliculaID = 6,
                            Actores = "Julia Roberts",
                            Descripcion = "Es una película de ciencia ficción española dirigida por Galder Gaztelu-Urrutia, lanzada en 2019. La película se centra en un centro de reclusión vertical donde los prisioneros están dispuestos en celdas apiladas, y una plataforma de comida desciende a través de los niveles, dejando a los prisioneros de los niveles superiores con menos comida.",
                            Director = "Ben Wheatley",
                            Imagen = "6.png",
                            Titulo = "EL HOYO"
                        },
                        new
                        {
                            PeliculaID = 7,
                            Actores = "Leonardo DiCaprio",
                            Descripcion = "En el colorido Reino Champiñón, Mario y Luigi disfrutan de una vida tranquila como fontaneros hasta que un día, Bowser, el rey de los Koopas, lanza un malévolo plan para robar todos los champiñones mágicos del reino.",
                            Director = "Alfred Hitchcock",
                            Imagen = "7.png",
                            Titulo = "SUPER MARIO BROS"
                        },
                        new
                        {
                            PeliculaID = 8,
                            Actores = "Meryl Streep",
                            Descripcion = "Un talentoso piloto de carreras que, después de una serie de eventos inesperados, se encuentra en la oportunidad de su vida: competir en el torneo de carreras 'Gran Turismo'.",
                            Director = "Quentin Tarantino",
                            Imagen = "8.png",
                            Titulo = "GRAN TURISMO"
                        },
                        new
                        {
                            PeliculaID = 9,
                            Actores = "Leonardo DiCaprio",
                            Descripcion = "En el colorido Reino Champiñón, Mario y Luigi disfrutan de una vida tranquila como fontaneros hasta que un día, Bowser, el rey de los Koopas, lanza un malévolo plan para robar todos los champiñones mágicos del reino.",
                            Director = "Ben Wheatley",
                            Imagen = "9.png",
                            Titulo = "SUPERMARIO BROS"
                        },
                        new
                        {
                            PeliculaID = 10,
                            Actores = "Meryl Streep",
                            Descripcion = "Un talentoso piloto de carreras que, después de una serie de eventos inesperados, se encuentra en la oportunidad de su vida: competir en el torneo de carreras 'Gran Turismo'.",
                            Director = "Quentin Tarantino",
                            Imagen = "10.png",
                            Titulo = "GRAN TURISMO"
                        });
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Reserva", b =>
                {
                    b.Property<int>("ReservaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaID"), 1L, 1);

                    b.Property<int>("SesionID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ReservaID");

                    b.HasIndex("SesionID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Reservas");

                    b.HasData(
                        new
                        {
                            ReservaID = 1,
                            SesionID = 1,
                            UsuarioID = 1
                        },
                        new
                        {
                            ReservaID = 2,
                            SesionID = 2,
                            UsuarioID = 1
                        });
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.ReservaButaca", b =>
                {
                    b.Property<int>("ReservaID")
                        .HasColumnType("int");

                    b.Property<int>("ButacaID")
                        .HasColumnType("int");

                    b.HasKey("ReservaID", "ButacaID");

                    b.HasIndex("ButacaID");

                    b.ToTable("ReservaButacas");

                    b.HasData(
                        new
                        {
                            ReservaID = 1,
                            ButacaID = 1
                        },
                        new
                        {
                            ReservaID = 1,
                            ButacaID = 2
                        },
                        new
                        {
                            ReservaID = 2,
                            ButacaID = 3
                        });
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Sala", b =>
                {
                    b.Property<int>("SalaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaID"), 1L, 1);

                    b.Property<string>("NombreSala")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SalaID");

                    b.ToTable("Salas");

                    b.HasData(
                        new
                        {
                            SalaID = 1,
                            NombreSala = "Sala 1"
                        },
                        new
                        {
                            SalaID = 2,
                            NombreSala = "Sala 2"
                        },
                        new
                        {
                            SalaID = 3,
                            NombreSala = "Sala 3"
                        },
                        new
                        {
                            SalaID = 4,
                            NombreSala = "Sala 4"
                        });
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Sesion", b =>
                {
                    b.Property<int>("SesionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SesionID"), 1L, 1);

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeliculaID")
                        .HasColumnType("int");

                    b.Property<int>("SalaID")
                        .HasColumnType("int");

                    b.HasKey("SesionID");

                    b.HasIndex("PeliculaID");

                    b.HasIndex("SalaID");

                    b.ToTable("Sesiones");

                    b.HasData(
                        new
                        {
                            SesionID = 1,
                            FechaHora = new DateTime(2024, 2, 29, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 1,
                            SalaID = 1
                        },
                        new
                        {
                            SesionID = 2,
                            FechaHora = new DateTime(2024, 3, 1, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 1,
                            SalaID = 1
                        },
                        new
                        {
                            SesionID = 3,
                            FechaHora = new DateTime(2024, 3, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 1,
                            SalaID = 2
                        },
                        new
                        {
                            SesionID = 4,
                            FechaHora = new DateTime(2024, 3, 1, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 2,
                            SalaID = 3
                        },
                        new
                        {
                            SesionID = 5,
                            FechaHora = new DateTime(2024, 3, 2, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 2,
                            SalaID = 4
                        },
                        new
                        {
                            SesionID = 6,
                            FechaHora = new DateTime(2024, 3, 1, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 3,
                            SalaID = 1
                        },
                        new
                        {
                            SesionID = 7,
                            FechaHora = new DateTime(2024, 3, 1, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 3,
                            SalaID = 2
                        },
                        new
                        {
                            SesionID = 8,
                            FechaHora = new DateTime(2024, 3, 2, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 3,
                            SalaID = 3
                        },
                        new
                        {
                            SesionID = 9,
                            FechaHora = new DateTime(2024, 3, 3, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 3,
                            SalaID = 4
                        },
                        new
                        {
                            SesionID = 10,
                            FechaHora = new DateTime(2024, 3, 2, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 4,
                            SalaID = 1
                        },
                        new
                        {
                            SesionID = 11,
                            FechaHora = new DateTime(2024, 3, 3, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 4,
                            SalaID = 2
                        },
                        new
                        {
                            SesionID = 12,
                            FechaHora = new DateTime(2024, 3, 2, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 5,
                            SalaID = 3
                        },
                        new
                        {
                            SesionID = 13,
                            FechaHora = new DateTime(2024, 3, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 5,
                            SalaID = 4
                        },
                        new
                        {
                            SesionID = 14,
                            FechaHora = new DateTime(2024, 3, 1, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 6,
                            SalaID = 1
                        },
                        new
                        {
                            SesionID = 15,
                            FechaHora = new DateTime(2024, 3, 2, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 6,
                            SalaID = 2
                        },
                        new
                        {
                            SesionID = 16,
                            FechaHora = new DateTime(2024, 3, 1, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 7,
                            SalaID = 3
                        },
                        new
                        {
                            SesionID = 17,
                            FechaHora = new DateTime(2024, 3, 2, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 7,
                            SalaID = 4
                        },
                        new
                        {
                            SesionID = 18,
                            FechaHora = new DateTime(2024, 3, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 8,
                            SalaID = 1
                        },
                        new
                        {
                            SesionID = 19,
                            FechaHora = new DateTime(2024, 3, 2, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 8,
                            SalaID = 2
                        },
                        new
                        {
                            SesionID = 20,
                            FechaHora = new DateTime(2024, 3, 3, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 8,
                            SalaID = 3
                        },
                        new
                        {
                            SesionID = 21,
                            FechaHora = new DateTime(2024, 3, 4, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 8,
                            SalaID = 4
                        },
                        new
                        {
                            SesionID = 22,
                            FechaHora = new DateTime(2024, 3, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 9,
                            SalaID = 1
                        },
                        new
                        {
                            SesionID = 23,
                            FechaHora = new DateTime(2024, 3, 3, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 9,
                            SalaID = 2
                        },
                        new
                        {
                            SesionID = 24,
                            FechaHora = new DateTime(2024, 3, 4, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 9,
                            SalaID = 3
                        },
                        new
                        {
                            SesionID = 25,
                            FechaHora = new DateTime(2024, 3, 5, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 9,
                            SalaID = 4
                        },
                        new
                        {
                            SesionID = 26,
                            FechaHora = new DateTime(2024, 3, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 10,
                            SalaID = 1
                        },
                        new
                        {
                            SesionID = 27,
                            FechaHora = new DateTime(2024, 3, 4, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 10,
                            SalaID = 2
                        },
                        new
                        {
                            SesionID = 28,
                            FechaHora = new DateTime(2024, 3, 5, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 10,
                            SalaID = 3
                        },
                        new
                        {
                            SesionID = 29,
                            FechaHora = new DateTime(2024, 3, 6, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 10,
                            SalaID = 4
                        });
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"), 1L, 1);

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("UsuarioID");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioID = 1,
                            Contrasena = "1234",
                            CorreoElectronico = "Alonsoalvira@gmail.com",
                            Nombre = "Juan",
                            Rol = 1
                        },
                        new
                        {
                            UsuarioID = 2,
                            Contrasena = "admin",
                            CorreoElectronico = "admin@gmail.com",
                            Nombre = "admin",
                            Rol = 1
                        });
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Butaca", b =>
                {
                    b.HasOne("ApiPeliculas.Modelos.Sala", "Sala")
                        .WithMany("Butacas")
                        .HasForeignKey("SalaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Reserva", b =>
                {
                    b.HasOne("ApiPeliculas.Modelos.Sesion", "Sesion")
                        .WithMany("Reservas")
                        .HasForeignKey("SesionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiPeliculas.Modelos.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sesion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.ReservaButaca", b =>
                {
                    b.HasOne("ApiPeliculas.Modelos.Butaca", "Butaca")
                        .WithMany("ReservaButacas")
                        .HasForeignKey("ButacaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiPeliculas.Modelos.Reserva", "Reserva")
                        .WithMany("ReservaButacas")
                        .HasForeignKey("ReservaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Butaca");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Sesion", b =>
                {
                    b.HasOne("ApiPeliculas.Modelos.Pelicula", "Pelicula")
                        .WithMany("Sesiones")
                        .HasForeignKey("PeliculaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiPeliculas.Modelos.Sala", "Sala")
                        .WithMany("Sesiones")
                        .HasForeignKey("SalaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pelicula");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Butaca", b =>
                {
                    b.Navigation("ReservaButacas");
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Pelicula", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Reserva", b =>
                {
                    b.Navigation("ReservaButacas");
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Sala", b =>
                {
                    b.Navigation("Butacas");

                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Sesion", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Usuario", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
