// <auto-generated />
using System;
using ApiPeliculas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(PeliculaContext))]
    partial class PeliculaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiPeliculas.Modelos.Butaca", b =>
                {
                    b.Property<int>("ButacaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ButacaID"), 1L, 1);

                    b.Property<int>("SalaID")
                        .HasColumnType("int");

                    b.HasKey("ButacaID");

                    b.HasIndex("SalaID");

                    b.ToTable("Butacas");

                    b.HasData(
                        new
                        {
                            ButacaID = 1,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 2,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 3,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 4,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 5,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 6,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 7,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 8,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 9,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 10,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 11,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 12,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 13,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 14,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 15,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 16,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 17,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 18,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 19,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 20,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 21,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 22,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 23,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 24,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 25,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 26,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 27,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 28,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 29,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 30,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 31,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 32,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 33,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 34,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 35,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 36,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 37,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 38,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 39,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 40,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 41,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 42,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 43,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 44,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 45,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 46,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 47,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 48,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 49,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 50,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 51,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 52,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 53,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 54,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 55,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 56,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 57,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 58,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 59,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 60,
                            SalaID = 1
                        },
                        new
                        {
                            ButacaID = 61,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 62,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 63,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 64,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 65,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 66,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 67,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 68,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 69,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 70,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 71,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 72,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 73,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 74,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 75,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 76,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 77,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 78,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 79,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 80,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 81,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 82,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 83,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 84,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 85,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 86,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 87,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 88,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 89,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 90,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 91,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 92,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 93,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 94,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 95,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 96,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 97,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 98,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 99,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 100,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 101,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 102,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 103,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 104,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 105,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 106,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 107,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 108,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 109,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 110,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 111,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 112,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 113,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 114,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 115,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 116,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 117,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 118,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 119,
                            SalaID = 2
                        },
                        new
                        {
                            ButacaID = 120,
                            SalaID = 2
                        });
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Pelicula", b =>
                {
                    b.Property<int>("PeliculaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeliculaID"), 1L, 1);

                    b.Property<string>("Actores")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PeliculaID");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            PeliculaID = 1,
                            Actores = "Philipe Marcus",
                            Descripcion = "Es una película de acción y ciencia ficción dirigida por Jon Turteltaub y estrenada en 2018. La trama gira en torno a un grupo de científicos que deben detener a un megalodón.",
                            Director = "Jon Turtle",
                            Imagen = "1.jpg",
                            Titulo = "THE MEG 2"
                        },
                        new
                        {
                            PeliculaID = 2,
                            Actores = "Martin Scorsese",
                            Descripcion = "Es una película de ciencia ficción española dirigida por Galder Gaztelu-Urrutia, lanzada en 2019. La película se centra en un centro de reclusión vertical donde los prisioneros están dispuestos en celdas apiladas, y una plataforma de comida desciende a través de los niveles, dejando a los prisioneros de los niveles superiores con menos comida.",
                            Director = "Galder Gaztelu-Urrutia",
                            Imagen = "2.png",
                            Titulo = "EL HOYO"
                        },
                        new
                        {
                            PeliculaID = 3,
                            Actores = "Leonardo DiCaprio",
                            Descripcion = "En el colorido Reino Champiñón, Mario y Luigi disfrutan de una vida tranquila como fontaneros hasta que un día, Bowser, el rey de los Koopas, lanza un malévolo plan para robar todos los champiñones mágicos del reino.",
                            Director = "Martin Scorsese",
                            Imagen = "3.png",
                            Titulo = "SUPER MARIO BROS"
                        },
                        new
                        {
                            PeliculaID = 4,
                            Actores = "Meryl Streep",
                            Descripcion = "Un talentoso piloto de carreras que, después de una serie de eventos inesperados, se encuentra en la oportunidad de su vida: competir en el torneo de carreras 'Gran Turismo'.",
                            Director = "Quentin Tarantino",
                            Imagen = "4.png",
                            Titulo = "GRAN TURISMO"
                        },
                        new
                        {
                            PeliculaID = 5,
                            Actores = "Philipe Marcus",
                            Descripcion = "Es una película de acción y ciencia ficción dirigida por Jon Turteltaub y estrenada en 2018. La trama gira en torno a un grupo de científicos que deben detener a un megalodón.",
                            Director = "Alfred Hitchcock",
                            Imagen = "5.jpg",
                            Titulo = "THE MEG 2"
                        },
                        new
                        {
                            PeliculaID = 6,
                            Actores = "Julia Roberts",
                            Descripcion = "Es una película de ciencia ficción española dirigida por Galder Gaztelu-Urrutia, lanzada en 2019. La película se centra en un centro de reclusión vertical donde los prisioneros están dispuestos en celdas apiladas, y una plataforma de comida desciende a través de los niveles, dejando a los prisioneros de los niveles superiores con menos comida.",
                            Director = "Ben Wheatley",
                            Imagen = "6.png",
                            Titulo = "EL HOYO"
                        },
                        new
                        {
                            PeliculaID = 7,
                            Actores = "Leonardo DiCaprio",
                            Descripcion = "En el colorido Reino Champiñón, Mario y Luigi disfrutan de una vida tranquila como fontaneros hasta que un día, Bowser, el rey de los Koopas, lanza un malévolo plan para robar todos los champiñones mágicos del reino.",
                            Director = "Alfred Hitchcock",
                            Imagen = "7.png",
                            Titulo = "SUPER MARIO BROS"
                        },
                        new
                        {
                            PeliculaID = 8,
                            Actores = "Meryl Streep",
                            Descripcion = "Un talentoso piloto de carreras que, después de una serie de eventos inesperados, se encuentra en la oportunidad de su vida: competir en el torneo de carreras 'Gran Turismo'.",
                            Director = "Quentin Tarantino",
                            Imagen = "8.png",
                            Titulo = "GRAN TURISMO"
                        },
                        new
                        {
                            PeliculaID = 9,
                            Actores = "Leonardo DiCaprio",
                            Descripcion = "En el colorido Reino Champiñón, Mario y Luigi disfrutan de una vida tranquila como fontaneros hasta que un día, Bowser, el rey de los Koopas, lanza un malévolo plan para robar todos los champiñones mágicos del reino.",
                            Director = "Ben Wheatley",
                            Imagen = "9.png",
                            Titulo = "SUPERMARIO BROS"
                        },
                        new
                        {
                            PeliculaID = 10,
                            Actores = "Meryl Streep",
                            Descripcion = "Un talentoso piloto de carreras que, después de una serie de eventos inesperados, se encuentra en la oportunidad de su vida: competir en el torneo de carreras 'Gran Turismo'.",
                            Director = "Quentin Tarantino",
                            Imagen = "10.png",
                            Titulo = "GRAN TURISMO"
                        });
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Reserva", b =>
                {
                    b.Property<int>("ReservaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaID"), 1L, 1);

                    b.Property<int>("SesionID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ReservaID");

                    b.HasIndex("SesionID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Reservas");

                    b.HasData(
                        new
                        {
                            ReservaID = 1,
                            SesionID = 1,
                            UsuarioID = 1
                        },
                        new
                        {
                            ReservaID = 2,
                            SesionID = 2,
                            UsuarioID = 1
                        });
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.ReservaButaca", b =>
                {
                    b.Property<int>("ReservaID")
                        .HasColumnType("int");

                    b.Property<int>("ButacaID")
                        .HasColumnType("int");

                    b.HasKey("ReservaID", "ButacaID");

                    b.HasIndex("ButacaID");

                    b.ToTable("ReservaButacas");

                    b.HasData(
                        new
                        {
                            ReservaID = 1,
                            ButacaID = 1
                        },
                        new
                        {
                            ReservaID = 1,
                            ButacaID = 2
                        },
                        new
                        {
                            ReservaID = 2,
                            ButacaID = 3
                        });
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Sala", b =>
                {
                    b.Property<int>("SalaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaID"), 1L, 1);

                    b.Property<string>("NombreSala")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SalaID");

                    b.ToTable("Salas");

                    b.HasData(
                        new
                        {
                            SalaID = 1,
                            NombreSala = "Sala 1"
                        },
                        new
                        {
                            SalaID = 2,
                            NombreSala = "Sala 2"
                        });
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Sesion", b =>
                {
                    b.Property<int>("SesionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SesionID"), 1L, 1);

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeliculaID")
                        .HasColumnType("int");

                    b.Property<int>("SalaID")
                        .HasColumnType("int");

                    b.HasKey("SesionID");

                    b.HasIndex("PeliculaID");

                    b.HasIndex("SalaID");

                    b.ToTable("Sesiones");

                    b.HasData(
                        new
                        {
                            SesionID = 1,
                            FechaHora = new DateTime(2024, 2, 29, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 1,
                            SalaID = 1
                        },
                        new
                        {
                            SesionID = 2,
                            FechaHora = new DateTime(2024, 2, 28, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            PeliculaID = 2,
                            SalaID = 2
                        });
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"), 1L, 1);

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("UsuarioID");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioID = 1,
                            Contrasena = "1234",
                            CorreoElectronico = "Alonsoalvira@gmail.com",
                            Nombre = "Juan",
                            Rol = 1
                        });
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Butaca", b =>
                {
                    b.HasOne("ApiPeliculas.Modelos.Sala", "Sala")
                        .WithMany("Butacas")
                        .HasForeignKey("SalaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Reserva", b =>
                {
                    b.HasOne("ApiPeliculas.Modelos.Sesion", "Sesion")
                        .WithMany("Reservas")
                        .HasForeignKey("SesionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiPeliculas.Modelos.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sesion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.ReservaButaca", b =>
                {
                    b.HasOne("ApiPeliculas.Modelos.Butaca", "Butaca")
                        .WithMany("ReservaButacas")
                        .HasForeignKey("ButacaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiPeliculas.Modelos.Reserva", "Reserva")
                        .WithMany("ReservaButacas")
                        .HasForeignKey("ReservaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Butaca");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Sesion", b =>
                {
                    b.HasOne("ApiPeliculas.Modelos.Pelicula", "Pelicula")
                        .WithMany("Sesiones")
                        .HasForeignKey("PeliculaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiPeliculas.Modelos.Sala", "Sala")
                        .WithMany("Sesiones")
                        .HasForeignKey("SalaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pelicula");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Butaca", b =>
                {
                    b.Navigation("ReservaButacas");
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Pelicula", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Reserva", b =>
                {
                    b.Navigation("ReservaButacas");
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Sala", b =>
                {
                    b.Navigation("Butacas");

                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Sesion", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ApiPeliculas.Modelos.Usuario", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
